<a href="https://colab.research.google.com/github/majidali321/Titanic_LogisticRegression/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score,precision_score,recall_score
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [3]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.drop('deck',axis=1,inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

filling NaN values

In [6]:
df['age'].fillna(df['age'].mean(),inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

<ipython-input-6-099675df06d7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)
<ipython-input-6-099675df06d7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)
<ipython-input-6-099675df06d7>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embark_town'].fillna(df['embark_town'].mode()[0],inplace=True)

In [7]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [11]:
X = df.drop('survived',axis=1)
y = df['survived']

X.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

# converting objects and catory in **int**

In [18]:
le = LabelEncoder()
for col in X.columns:
  if X[col].dtype == 'object' or X[col].dtype.name == 'category':
    X[col] = le.fit_transform(X[col])

X.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [19]:
X.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [20]:
X_train,X_test,y_train,y_test  = train_test_split(X ,y,test_size=0.2)

In [21]:
model = LogisticRegression()
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

predict the values

In [22]:
y_pred = model.predict(X_test)

evaluate the model

In [23]:
print('Accuracy score' ,accuracy_score(y_test,y_pred))
print('confusion matrix')
print(confusion_matrix(y_test,y_pred))
print('classification report')
print(classification_report(y_test,y_pred))
print('f1 score',f1_score(y_test,y_pred))
print('precision score',precision_score(y_test,y_pred))
print('recall score',recall_score(y_test,y_pred))

Accuracy score 1.0
confusion matrix
[[102   0]
 [  0  77]]
classification report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       102
           1       1.00      1.00      1.00        77

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

f1 score 1.0
precision score 1.0
recall score 1.0

In [25]:
import pickle
pickle.dump(model,open('Logistic_Regression_model.pkl','wb'))

In [26]:
# For Scikit-learn Logistic Regression Model
from sklearn.linear_model import LogisticRegression
import joblib
from google.colab import files

# Assuming `model` is your trained logistic regression model
joblib.dump(model, 'logistic_model.pkl')  # Save the model to a file

# Download the saved model to your PC
files.download('logistic_model.pkl')